class Absolute(object):
    MEMCACHED_YML = '~/asl18/experimentation/memcached.yml'
    MEMTIER_YML = '~/asl18/experimentation/memtier.yml'
    PRIVATE_KEY = '~/.ssh/id_rsa'
    PUBLIC_KEY = '~/.ssh/id_rsa.pub'
    SERVER_CONFIG = '~/asl18/experimentation/servers.json'
    TESTS = '~/asl18/experimentation/tests'
    CURRENT_TESTS = '~/asl18/experimentation/tests/current'
    BUILD_XML = '~/asl18/build.xml'
    JAR_FILE = '~/asl18/dist/middleware-ajilm.jar'
    FILL_LOGS = '~/fill/'
    REMOTE_LOGS = '~/logs/'
